services:
  # Backend API
  - type: web
    name: cmms-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma db push --accept-data-loss && node dist/src/main.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  # Frontend
  - type: web
    name: cmms-frontend
    runtime: node
    region: singapore
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
