services:
  # Backend API
  - type: web
    name: cmms-backend
    runtime: node
    region: singapore
    plan: free
    rootDirectory: backend
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && node dist/src/main.js
    envVars:
      - key: DATABASE_URL
        value: file:./prod.db
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
    healthCheckPath: /api

  # Frontend
  - type: web
    name: cmms
    runtime: node
    region: singapore
    plan: free
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NODE_ENV
        value: production
